// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenGitBase.Common.Data;

#nullable disable

namespace OpenGitBase.Common.Migrations
{
    [DbContext(typeof(OpenGitBaseDbContext))]
    [Migration("20260710212728_AddRepositoryMaxBytesOverride")]
    partial class AddRepositoryMaxBytesOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.CommentAnchorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.ToTable("comment_anchors", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionCommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("DiscussionId", "ParentCommentId", "CreatedAt");

                    b.ToTable("discussion_comments", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasEverBeenEngaged")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Number")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "UpdatedAt");

                    b.ToTable("discussions", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionSubscriptionEntity", b =>
                {
                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DiscussionId", "UserId");

                    b.ToTable("discussion_subscriptions", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionTagAssignmentEntity", b =>
                {
                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("DiscussionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("discussion_tag_assignments", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.RepositoryBlockedUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BlockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "UserId")
                        .IsUnique();

                    b.ToTable("repository_blocked_users", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.RepositoryTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("repository_tags", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.UserNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("UserId", "ReadAt", "CreatedAt");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.GitAccessToken.Entities.GitAccessTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TokenLookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TokenLookupHash")
                        .IsUnique();

                    b.ToTable("GitAccessToken", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.MergeRequest.Entities.MergeRequestApprovalEntity", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MergeRequestId", "UserId");

                    b.ToTable("merge_request_approvals", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.MergeRequest.Entities.MergeRequestDiscussionLinkEntity", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.HasKey("MergeRequestId", "DiscussionId", "RelationshipType");

                    b.ToTable("merge_request_discussion_links", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.MergeRequest.Entities.MergeRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<string>("MergeCommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceHeadSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBaseSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Number")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "UpdatedAt");

                    b.HasIndex("RepositoryId", "SourceRef", "TargetRef");

                    b.ToTable("merge_requests", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationInviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailCiphertext")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EmailLookupHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OrganizationId", "EmailLookupHash");

                    b.ToTable("OrganizationInvite", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMember", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationStorageSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultPlacementPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultSelfHostPreference")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("OrganizationStorageSettings", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.PublicGitSshKey.Entities.PublicGitSshKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicSSHKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("PublicSSHKey")
                        .IsUnique();

                    b.HasIndex("Fingerprint", "PublicSSHKey");

                    b.HasIndex("OwnerUserId", "Fingerprint");

                    b.ToTable("PublicGitSshKey", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.ProtectedBranchAllowedUserEntity", b =>
                {
                    b.Property<Guid>("ProtectedBranchRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProtectedBranchRuleId", "UserId");

                    b.ToTable("ProtectedBranchAllowedUser", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.ProtectedBranchRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedPushRoles")
                        .HasColumnType("integer");

                    b.Property<bool>("BlockDirectPush")
                        .HasColumnType("boolean");

                    b.Property<bool>("DismissApprovalsOnPush")
                        .HasColumnType("boolean");

                    b.Property<int>("ForcePushPolicy")
                        .HasColumnType("integer");

                    b.Property<int?>("LockedMergeStrategy")
                        .HasColumnType("integer");

                    b.Property<int>("MergeRoleThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequireMergeRequest")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredApprovalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Pattern")
                        .IsUnique();

                    b.ToTable("ProtectedBranchRule", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.PushRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProtectedBranchRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProtectedBranchRuleId");

                    b.ToTable("PushRule", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultBranchName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<long?>("MaxBytesOverride")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhysicalPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("PlacementPolicy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryStorageNodeId")
                        .HasColumnType("uuid");

                    b.Property<long>("PrimaryWatermark")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ReadReplicaStorageNodeId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReplicationEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("ReplicationState")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("StorageBytesUsed")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StorageNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "OwnerUserId")
                        .IsUnique();

                    b.ToTable("Repository", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyCiphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("RepositoryKey", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryReplicaEntity", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageNodeId")
                        .HasColumnType("uuid");

                    b.Property<long>("AppliedWatermark")
                        .HasColumnType("bigint");

                    b.Property<long?>("ArtifactWatermark")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("RepositoryId", "StorageNodeId");

                    b.ToTable("RepositoryReplica", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.RepositoryMember.Entities.RepositoryMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RepositoryId", "UserId")
                        .IsUnique();

                    b.ToTable("RepositoryMember", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Status.Entities.FleetComponentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProbeUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentType", "InstanceId")
                        .IsUnique();

                    b.ToTable("FleetComponent", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Status.Entities.StatusHistoryHourlyBucketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ComponentGroup")
                        .HasColumnType("integer");

                    b.Property<int>("DegradedSamples")
                        .HasColumnType("integer");

                    b.Property<int>("HealthySamples")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalSamples")
                        .HasColumnType("integer");

                    b.Property<int>("UnhealthySamples")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentGroup", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("StatusHistoryHourlyBucket", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Status.Entities.StatusIncidentBannerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StatusIncidentBanner", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Status.Entities.StatusSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatusSnapshot", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.StorageNode.Entities.FleetSecretsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DispatcherSshPrivateKeyProtected")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)");

                    b.Property<string>("DispatcherSshPublicKey")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("FleetBootstrapTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FleetSecrets", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.StorageNode.Entities.StorageNodeEnrollmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnrollmentTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostingScope")
                        .HasColumnType("integer");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.ToTable("StorageNodeEnrollment", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.StorageNode.Entities.StorageNodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiTokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ApiTokenProtected")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CertificateThumbprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FreeBytesAvailable")
                        .HasColumnType("bigint");

                    b.Property<int>("HostingScope")
                        .HasColumnType("integer");

                    b.Property<int>("InternalGitHttpPort")
                        .HasColumnType("integer");

                    b.Property<string>("InternalHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("InternalHttpPort")
                        .HasColumnType("integer");

                    b.Property<int>("InternalSshPort")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MaxBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OwnerOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalBytesAvailable")
                        .HasColumnType("bigint");

                    b.Property<long>("UsedBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("StorageNode", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Users.Entities.UserCredentialsEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailCiphertext")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EmailLookupHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("EmailVerificationTokenExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("InternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("SignInProvider")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.HasIndex("EmailLookupHash")
                        .IsUnique();

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Users.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.CommentAnchorEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionCommentEntity", "Comment")
                        .WithOne("Anchor")
                        .HasForeignKey("OpenGitBase.Features.Discussion.Entities.CommentAnchorEntity", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionCommentEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", "Discussion")
                        .WithMany("Comments")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionCommentEntity", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Discussion");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionSubscriptionEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", "Discussion")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionTagAssignmentEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", "Discussion")
                        .WithMany("TagAssignments")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenGitBase.Features.Discussion.Entities.RepositoryTagEntity", "Tag")
                        .WithMany("Assignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.UserNotificationEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", "Discussion")
                        .WithMany()
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");
                });

            modelBuilder.Entity("OpenGitBase.Features.GitAccessToken.Entities.GitAccessTokenEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("OpenGitBase.Features.MergeRequest.Entities.MergeRequestApprovalEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.MergeRequest.Entities.MergeRequestEntity", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("OpenGitBase.Features.MergeRequest.Entities.MergeRequestDiscussionLinkEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.MergeRequest.Entities.MergeRequestEntity", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationInviteEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Organization.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("OpenGitBase.Features.Organization.Entities.OrganizationMemberEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Organization.Entities.OrganizationEntity", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenGitBase.Features.PublicGitSshKey.Entities.PublicGitSshKeyEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.ProtectedBranchAllowedUserEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Repository.Entities.ProtectedBranchRuleEntity", "ProtectedBranchRule")
                        .WithMany("AllowedUsers")
                        .HasForeignKey("ProtectedBranchRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtectedBranchRule");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.PushRuleEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Repository.Entities.ProtectedBranchRuleEntity", "ProtectedBranchRule")
                        .WithMany("PushRules")
                        .HasForeignKey("ProtectedBranchRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtectedBranchRule");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryKeyEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Repository.Entities.RepositoryEntity", "Repository")
                        .WithOne()
                        .HasForeignKey("OpenGitBase.Features.Repository.Entities.RepositoryKeyEntity", "RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryReplicaEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Repository.Entities.RepositoryEntity", "Repository")
                        .WithMany("Replicas")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OpenGitBase.Features.RepositoryMember.Entities.RepositoryMemberEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Repository.Entities.RepositoryEntity", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenGitBase.Features.Users.Entities.UserCredentialsEntity", b =>
                {
                    b.HasOne("OpenGitBase.Features.Users.Entities.UserEntity", "User")
                        .WithOne("UserCredentials")
                        .HasForeignKey("OpenGitBase.Features.Users.Entities.UserCredentialsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionCommentEntity", b =>
                {
                    b.Navigation("Anchor");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.DiscussionEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Subscriptions");

                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("OpenGitBase.Features.Discussion.Entities.RepositoryTagEntity", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.ProtectedBranchRuleEntity", b =>
                {
                    b.Navigation("AllowedUsers");

                    b.Navigation("PushRules");
                });

            modelBuilder.Entity("OpenGitBase.Features.Repository.Entities.RepositoryEntity", b =>
                {
                    b.Navigation("Replicas");
                });

            modelBuilder.Entity("OpenGitBase.Features.Users.Entities.UserEntity", b =>
                {
                    b.Navigation("UserCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
