#!/usr/bin/env bash
# Bootstrap fleet SSH keys and storage node enrollments via admin API.
set -euo pipefail

API_URL="${API_URL:-http://localhost:8080}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PKI_SCRIPT="${REPO_ROOT}/docker/pki/generate-node-pki.sh"
OVERRIDE_FILE="${OVERRIDE_FILE:-${REPO_ROOT}/docker-compose.override.yml}"
EXAMPLE_FILE="${EXAMPLE_FILE:-${REPO_ROOT}/docker-compose.override.example.yml}"

if [ -x "${PKI_SCRIPT}" ]; then
  echo "==> Generating storage node certificates"
  "${PKI_SCRIPT}"
fi

ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASS="${ADMIN_PASS:-change-me-admin}"

login() {
  curl -fsS -X POST "${API_URL}/signin/login" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${ADMIN_USER}\",\"password\":\"${ADMIN_PASS}\"}"
}

echo "==> Signing in as admin"
TOKEN=$(login | tr -d '\n\r')

echo "==> Generating dispatcher SSH keys"
FLEET_JSON=$(curl -fsS -X POST "${API_URL}/admin/fleet/dispatcher-ssh-keys/generate" \
  -H "Authorization: Bearer ${TOKEN}")
FLEET_BOOTSTRAP_TOKEN=$(echo "${FLEET_JSON}" | python3 -c 'import json,sys; print(json.load(sys.stdin)["fleetBootstrapToken"])')
DISPATCHER_SSH_PUBLIC_KEY=$(echo "${FLEET_JSON}" | python3 -c 'import json,sys; print(json.load(sys.stdin)["dispatcherSshPublicKey"])')

create_enrollment() {
  local node_id="$1"
  curl -fsS -X POST "${API_URL}/admin/storage-enrollments" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"nodeId\":\"${node_id}\"}" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin)["enrollmentToken"])'
}

echo "==> Creating storage enrollments"
STORAGE_1_TOKEN=$(create_enrollment storage-1)
STORAGE_2_TOKEN=$(create_enrollment storage-2)

if [ ! -f "${OVERRIDE_FILE}" ]; then
  if [ ! -f "${EXAMPLE_FILE}" ]; then
    echo "Missing ${EXAMPLE_FILE}" >&2
    exit 1
  fi
  cp "${EXAMPLE_FILE}" "${OVERRIDE_FILE}"
  echo "Created ${OVERRIDE_FILE} from example — set REPLACE_WITH_CLOUDFLARE_TUNNEL_TOKEN before starting the tunnel"
fi

python3 - "${OVERRIDE_FILE}" "${STORAGE_1_TOKEN}" "${STORAGE_2_TOKEN}" "${FLEET_BOOTSTRAP_TOKEN}" "${DISPATCHER_SSH_PUBLIC_KEY}" <<'PY'
import json
import re
import sys
from pathlib import Path

override_path = Path(sys.argv[1])
storage_1 = sys.argv[2]
storage_2 = sys.argv[3]
fleet_token = sys.argv[4]
dispatcher_key = sys.argv[5]

cloudflare_token = "REPLACE_WITH_CLOUDFLARE_TUNNEL_TOKEN"
legacy_env = override_path.parent / "docker" / ".env"
if legacy_env.exists():
    for line in legacy_env.read_text().splitlines():
        if line.startswith("CLOUDFLARE_TUNNEL_KEY="):
            value = line.split("=", 1)[1].strip().strip('"')
            if value:
                cloudflare_token = value
if override_path.exists():
    match = re.search(r"--token (\S+)", override_path.read_text())
    if match and match.group(1) != "REPLACE_WITH_CLOUDFLARE_TUNNEL_TOKEN":
        cloudflare_token = match.group(1)

def q(value: str) -> str:
    return json.dumps(value)

content = f"""# Generated by scripts/bootstrap-fleet.sh — do not commit
# Template: docker-compose.override.example.yml

services:
  storage-1:
    environment:
      STORAGE_ENROLLMENT_TOKEN: {q(storage_1)}
      DISPATCHER_SSH_PUBLIC_KEY: {q(dispatcher_key)}

  storage-2:
    environment:
      STORAGE_ENROLLMENT_TOKEN: {q(storage_2)}
      DISPATCHER_SSH_PUBLIC_KEY: {q(dispatcher_key)}

  dispatcher-1:
    environment:
      FLEET_BOOTSTRAP_TOKEN: {q(fleet_token)}

  dispatcher-2:
    environment:
      FLEET_BOOTSTRAP_TOKEN: {q(fleet_token)}

  web:
    build:
      args:
        NUXT_PUBLIC_INSTANCE_NAME: OpenGitBase
        NUXT_PUBLIC_API_BASE: /api
        NUXT_PUBLIC_SITE_GATE_ENABLED: "true"

  opengitbase_cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: opengitbase_cloudflare_tunnel
    depends_on:
      api:
        condition: service_started
      web:
        condition: service_started
    restart: always
    command: tunnel --no-autoupdate run --url http://api:8080 --token {cloudflare_token}
"""

override_path.write_text(content)
print(f"Wrote {override_path}")
PY

echo "Start the stack with:"
echo "  docker compose -f docker-compose.yml -f docker-compose.override.yml up -d --build"
